CREATE TABLE IF NOT EXISTS Users (
    `id` VARCHAR(36) PRIMARY KEY DEFAULT SUBSTRING(REPLACE(UUID(), '-', ''), 1, 10),
    `firstName` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    UNIQUE KEY(email)
);
